packages:
  - apps/*
  - packages/*

allowBuilds:
  '@nestjs/core': false
  '@prisma/client': false
  '@prisma/engines': false
  msgpackr-extract: false
  prisma: false
  sharp: false
  unrs-resolver: false

overrides:
  '@nestjs/core@<=11.1.17': '>=11.1.18'
  ajv@>=7.0.0-alpha.0 <8.18.0: '>=8.18.0'
  axios@>=1.0.0 <1.15.0: '>=1.15.0'
  brace-expansion@<1.1.13: '>=1.1.13'
  brace-expansion@>=2.0.0 <2.0.3: '>=2.0.3'
  fast-xml-parser@<5.7.0: '>=5.7.0'
  file-type@>=13.0.0 <21.3.1: '>=21.3.1'
  file-type@>=20.0.0 <=21.3.1: '>=21.3.2'
  follow-redirects@<=1.15.11: '>=1.16.0'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  handlebars@>=4.0.0 <4.7.9: '>=4.7.9'
  handlebars@>=4.0.0 <=4.7.8: '>=4.7.9'
  handlebars@>=4.6.0 <=4.7.8: '>=4.7.9'
  lodash@<=4.17.23: '>=4.18.0'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
  lodash@>=4.0.0 <=4.17.23: '>=4.18.0'
  multer@<2.1.0: '>=2.1.0'
  multer@<2.1.1: '>=2.1.1'
  next@>=16.0.0-beta.0 <16.2.3: '>=16.2.3'
  path-to-regexp@<0.1.13: '>=0.1.13'
  picomatch@<2.3.2: '>=2.3.2'
  picomatch@>=4.0.0 <4.0.4: '>=4.0.4'
  postcss@<8.5.10: '>=8.5.10'
  tmp@<=0.2.3: '>=0.2.4'
  uuid@<14.0.0: '>=14.0.0'
  vite@<=6.4.1: '>=6.4.2'
  vite@>=6.0.0 <=6.4.1: '>=6.4.2'
  webpack@>=5.49.0 <5.104.0: '>=5.104.0'
  webpack@>=5.49.0 <=5.104.0: '>=5.104.1'
