/**
 * All API error codes for Savdo.
 * Full taxonomy: docs/V1.1/05_error_taxonomy.md
 */
export const ErrorCode = {
  // AUTH
  OTP_NOT_FOUND: 'OTP_NOT_FOUND',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_INVALID: 'OTP_INVALID',
  OTP_ALREADY_CONSUMED: 'OTP_ALREADY_CONSUMED',
  OTP_TOO_MANY_ATTEMPTS: 'OTP_TOO_MANY_ATTEMPTS',
  OTP_SEND_LIMIT: 'OTP_SEND_LIMIT',
  TELEGRAM_NOT_LINKED: 'TELEGRAM_NOT_LINKED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',

  // AUTHZ
  FORBIDDEN: 'FORBIDDEN',
  SELLER_BLOCKED: 'SELLER_BLOCKED',
  STORE_NOT_APPROVED: 'STORE_NOT_APPROVED',
  STORE_SUSPENDED: 'STORE_SUSPENDED',
  NOT_STORE_OWNER: 'NOT_STORE_OWNER',
  NOT_PRODUCT_OWNER: 'NOT_PRODUCT_OWNER',
  NOT_ORDER_PARTICIPANT: 'NOT_ORDER_PARTICIPANT',
  NOT_THREAD_PARTICIPANT: 'NOT_THREAD_PARTICIPANT',
  ADMIN_ONLY: 'ADMIN_ONLY',

  // VALIDATION
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_PHONE: 'INVALID_PHONE',
  INVALID_SLUG: 'INVALID_SLUG',
  SLUG_TOO_SHORT: 'SLUG_TOO_SHORT',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',

  // CATEGORIES
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  STORE_CATEGORY_LIMIT: 'STORE_CATEGORY_LIMIT',

  // STORE
  STORE_ALREADY_EXISTS: 'STORE_ALREADY_EXISTS',
  STORE_NOT_FOUND: 'STORE_NOT_FOUND',
  STORE_SLUG_TAKEN: 'STORE_SLUG_TAKEN',
  STORE_SLUG_IMMUTABLE: 'STORE_SLUG_IMMUTABLE',
  STORE_ONBOARDING_INCOMPLETE: 'STORE_ONBOARDING_INCOMPLETE',
  STORE_INVALID_TRANSITION: 'STORE_INVALID_TRANSITION',

  // PRODUCT
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  VARIANT_NOT_FOUND: 'VARIANT_NOT_FOUND',
  OPTION_GROUP_NOT_FOUND: 'OPTION_GROUP_NOT_FOUND',
  OPTION_VALUE_NOT_FOUND: 'OPTION_VALUE_NOT_FOUND',
  PRODUCT_NOT_ACTIVE: 'PRODUCT_NOT_ACTIVE',
  SKU_ALREADY_EXISTS: 'SKU_ALREADY_EXISTS',
  PRODUCT_INVALID_TRANSITION: 'PRODUCT_INVALID_TRANSITION',
  PRODUCT_DELETE_ACTIVE: 'PRODUCT_DELETE_ACTIVE',
  PRODUCT_PRICE_INVALID: 'PRODUCT_PRICE_INVALID',

  // CART
  CART_NOT_FOUND: 'CART_NOT_FOUND',
  CART_STORE_MISMATCH: 'CART_STORE_MISMATCH',
  CART_EMPTY: 'CART_EMPTY',
  CART_EXPIRED: 'CART_EXPIRED',
  CART_ITEM_NOT_FOUND: 'CART_ITEM_NOT_FOUND',

  // CHECKOUT
  CHECKOUT_ITEMS_UNAVAILABLE: 'CHECKOUT_ITEMS_UNAVAILABLE',
  CHECKOUT_STOCK_INSUFFICIENT: 'CHECKOUT_STOCK_INSUFFICIENT',

  // ORDERS
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_INVALID_TRANSITION: 'ORDER_INVALID_TRANSITION',
  ORDER_IMMUTABLE: 'ORDER_IMMUTABLE',
  ORDER_ACCESS_DENIED: 'ORDER_ACCESS_DENIED',
  CROSS_STORE_ORDER: 'CROSS_STORE_ORDER',
  CANCEL_REASON_REQUIRED: 'CANCEL_REASON_REQUIRED',

  // CHAT
  THREAD_NOT_FOUND: 'THREAD_NOT_FOUND',
  THREAD_ALREADY_EXISTS: 'THREAD_ALREADY_EXISTS',
  THREAD_CLOSED: 'THREAD_CLOSED',
  BUYER_NOT_IDENTIFIED: 'BUYER_NOT_IDENTIFIED',
  CHAT_NOT_FOUND: 'CHAT_NOT_FOUND',
  CHAT_ACCESS_DENIED: 'CHAT_ACCESS_DENIED',
  CHAT_THREAD_EXISTS: 'CHAT_THREAD_EXISTS',
  CHAT_DISABLED: 'CHAT_DISABLED',

  // MEDIA
  MEDIA_NOT_FOUND: 'MEDIA_NOT_FOUND',
  MEDIA_NOT_OWNED: 'MEDIA_NOT_OWNED',
  MEDIA_LIMIT_EXCEEDED: 'MEDIA_LIMIT_EXCEEDED',
  MEDIA_UPLOAD_TYPE_NOT_ALLOWED: 'MEDIA_UPLOAD_TYPE_NOT_ALLOWED',
  MEDIA_UPLOAD_FAILED: 'MEDIA_UPLOAD_FAILED',
  MEDIA_ALREADY_CONFIRMED: 'MEDIA_ALREADY_CONFIRMED',
  MEDIA_SIZE_EXCEEDED: 'MEDIA_SIZE_EXCEEDED',
  UPLOAD_FAILED: 'UPLOAD_FAILED',

  // NOTIFICATIONS
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',

  // MODERATION
  MODERATION_CASE_NOT_FOUND: 'MODERATION_CASE_NOT_FOUND',
  MODERATION_COMMENT_REQUIRED: 'MODERATION_COMMENT_REQUIRED',
  MODERATION_INVALID_ACTION: 'MODERATION_INVALID_ACTION',

  // ADMIN
  ADMIN_NOT_FOUND: 'ADMIN_NOT_FOUND',
  ADMIN_USER_ALREADY_SUSPENDED: 'ADMIN_USER_ALREADY_SUSPENDED',
  ADMIN_STORE_ALREADY_SUSPENDED: 'ADMIN_STORE_ALREADY_SUSPENDED',
  ADMIN_STORE_ALREADY_REJECTED: 'ADMIN_STORE_ALREADY_REJECTED',
  ADMIN_STORE_ALREADY_ARCHIVED: 'ADMIN_STORE_ALREADY_ARCHIVED',

  // GENERIC
  CONFLICT: 'CONFLICT',

  // SYSTEM
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  NOT_FOUND: 'NOT_FOUND',
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];
